version: 2.1

orbs:
  codacy: codacy/base@2.2.1
  codacy_plugins_test: codacy/plugins-test@0.15.4

workflows:
  version: 2
  compile_test_deploy:
    jobs:
      - codacy/checkout_and_version
      - codacy/shell:
          name: publish_docker_local
          cmd: |
            docker build -t $CIRCLE_PROJECT_REPONAME:latest .
            docker save --output docker-image.tar $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - codacy/checkout_and_version
      - codacy/shell:
          name: test_with_eslintrc
          cmd: |
            # codacy-plugins-test can't test metrics with config filters
            # test if tool ignores custom eslintrc files
            docker load --input docker-image.tar

            echo "plugins:" > eslint_config
            echo "  - jest" >> eslint_config

            docker run -v $PWD/docs/tests/:/src -v $PWD/eslint_config:/src/.eslintrc.yaml $CIRCLE_PROJECT_REPONAME:latest
          persist_to_workspace: true
          requires:
            - publish_docker_local
      - codacy_plugins_test/run:
          name: plugins_test
          run_metrics_tests: true
          run_json_tests: false
          run_pattern_tests: false
          requires:
            - publish_docker_local
      - codacy/publish_docker:
          context: CodacyDocker
          requires:
            - test_with_eslintrc
            - plugins_test
          filters:
            branches:
              only:
                - master
      - codacy/tag_version:
          name: tag_version
          context: CodacyAWS
          requires:
            - codacy/publish_docker
